# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dofbot_pro_info/cur_jointRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class cur_jointRequest(genpy.Message):
  _md5sum = "316e22b41dfc06dd91c3544d4b9ba5ed"
  _type = "dofbot_pro_info/cur_jointRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# request
string  srv_joints
"""
  __slots__ = ['srv_joints']
  _slot_types = ['string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       srv_joints

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(cur_jointRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.srv_joints is None:
        self.srv_joints = ''
    else:
      self.srv_joints = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.srv_joints
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.srv_joints = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.srv_joints = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.srv_joints
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.srv_joints = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.srv_joints = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dofbot_pro_info/cur_jointResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class cur_jointResponse(genpy.Message):
  _md5sum = "2a8aa04b9b18701c3796ea044e492219"
  _type = "dofbot_pro_info/cur_jointResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# response
float64 srv_joint1
float64 srv_joint2
float64 srv_joint3
float64 srv_joint4
float64 srv_joint5
float64 srv_joint6

"""
  __slots__ = ['srv_joint1','srv_joint2','srv_joint3','srv_joint4','srv_joint5','srv_joint6']
  _slot_types = ['float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       srv_joint1,srv_joint2,srv_joint3,srv_joint4,srv_joint5,srv_joint6

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(cur_jointResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.srv_joint1 is None:
        self.srv_joint1 = 0.
      if self.srv_joint2 is None:
        self.srv_joint2 = 0.
      if self.srv_joint3 is None:
        self.srv_joint3 = 0.
      if self.srv_joint4 is None:
        self.srv_joint4 = 0.
      if self.srv_joint5 is None:
        self.srv_joint5 = 0.
      if self.srv_joint6 is None:
        self.srv_joint6 = 0.
    else:
      self.srv_joint1 = 0.
      self.srv_joint2 = 0.
      self.srv_joint3 = 0.
      self.srv_joint4 = 0.
      self.srv_joint5 = 0.
      self.srv_joint6 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.srv_joint1, _x.srv_joint2, _x.srv_joint3, _x.srv_joint4, _x.srv_joint5, _x.srv_joint6))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.srv_joint1, _x.srv_joint2, _x.srv_joint3, _x.srv_joint4, _x.srv_joint5, _x.srv_joint6,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.srv_joint1, _x.srv_joint2, _x.srv_joint3, _x.srv_joint4, _x.srv_joint5, _x.srv_joint6))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.srv_joint1, _x.srv_joint2, _x.srv_joint3, _x.srv_joint4, _x.srv_joint5, _x.srv_joint6,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
class cur_joint(object):
  _type          = 'dofbot_pro_info/cur_joint'
  _md5sum = '7bf4e10c269e4b461f9707a22ed78be1'
  _request_class  = cur_jointRequest
  _response_class = cur_jointResponse
