(cl:defpackage dofbot_pro_info-srv
  (:use )
  (:export
   "CUR_JOINT"
   "<CUR_JOINT-REQUEST>"
   "CUR_JOINT-REQUEST"
   "<CUR_JOINT-RESPONSE>"
   "CUR_JOINT-RESPONSE"
   "DOFBOT_PRO_KINEMARICS"
   "<DOFBOT_PRO_KINEMARICS-REQUEST>"
   "DOFBOT_PRO_KINEMARICS-REQUEST"
   "<DOFBOT_PRO_KINEMARICS-RESPONSE>"
   "DOFBOT_PRO_KINEMARICS-RESPONSE"
   "KINEMARICS"
   "<KINEMARICS-REQUEST>"
   "KINEMARICS-REQUEST"
   "<KINEMARICS-RESPONSE>"
   "KINEMARICS-RESPONSE"
  ))

